---

- name: "configuration play." 
  hosts: web
  remote_user: ubuntu
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
    os_environment:
      - key: NODE_ENV
        value: production
      - key: VERSION
        value: 1
      - key: TYPEORM_CONNECTION
        value: postgres
      - key: TYPEORM_MIGRATIONS_DIR
        value: ./src/migrations
      - key: TYPEORM_ENTITIES
        value: ./src/modules/domain/**/*.entity.ts
      - key: TYPEORM_MIGRATIONS
        value: ./src/migrations/*.ts
      - key: TYPEORM_HOST
        value: database-1.czwr0c213uee.us-east-1.rds.amazonaws.com
      - key: TYPEORM_PORT
        value: 5432
      - key: TYPEORM_USERNAME
        value: postgres
      - key: TYPEORM_PASSWORD
        value: password
      - key: TYPEORM_DATABASE
        value: glee
    
  environment:
    NODE_ENV: production
    VERSION: "1"
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

  pre_tasks:
    - name: customize /etc/environment
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ os_environment }}"

    - name: "wait-max 600 seconds for target connection to become reachable/usable."
      wait_for_connection: 
        timeout: 600

    - name: "install python for Ansible."
      become: true
      shell: apt -y update && apt install -y python3

  roles:
    - deploy
  
