---
- name: Create backend directory
  file:
    path: ~/backend
    state: directory

- name: unarchive the artifact 
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: isnstall node dep
  shell: |
    cd ~/backend
    npm install

- name: test ls in backend
  shell: | 
    cd ~/backend
    ls -la
    ls dist
  register: lol

- name: testing
  debug:
    msg: "{{lol.stdout.lines}}"


- name: running the app
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
  register: run_node

- name: checking node
  debug:
    msg: "{{run_node.stdout.lines}}"
 