version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run: cd frontend
      - run: npm install
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - run:
          name: Build front-end
          command: npm run build
        
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run: cd backend
      - run: npm install
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - run:
          name: Build back-end
          command: npm run build
        
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend